### ISSUE TITLE
Error from beta version

### ISSUE THREAD

**Issue by cailmaminiaina** [Bes-js/Hercai.py#2]
https://hercai.onrender.com/beta/hercai?question=hello

{"status":404,"message":"Prompt Error!"}

**Comment by cailmaminiaina** [comment]
then same error for V3 model

**Comment by Bes-js** [comment]
fixed.

**Comment by cailmaminiaina** [comment]
not yet!!

**Comment by Bes-js** [comment]
use v3 model or someone avaible model

**Comment by cailmaminiaina** [comment]
> use v3 model or someone avaible model

Done but i need the conversation history with the user_id
